### ISSUE TITLE
Post request in License giving internal server error

### ISSUE THREAD

**Issue by bhowmik94** [fossology/LicenseDb#28]

**Comment by GMishx** [comment]
Hey @bhowmik94 , can you please provide more info about the error?

Please include the sample request and the logs.

**Comment by bhowmik94** [comment]
Hi @GMishx, I am giving the http request and response here - 
![req](https://github.com/fossology/LicenseDb/assets/25108210/390e8de7-e1af-431c-8dc3-4cc948df51f9)
![res](https://github.com/fossology/LicenseDb/assets/25108210/637b0d8e-fb0d-4d22-941d-f5b416f7c811)

Can you tell me, where do I find the logs?

**Comment by GMishx** [comment]
It will be very helpful if you can paste the `curl` command so I can replicate it at my end.

And the output should be in the shell here `laas` is running.

**Comment by bhowmik94** [comment]
Sure, here is the curl command - 

curl -X 'POST' \
  'http://localhost:8080/api/v1/licenses' \
  -H 'accept: application/json' \
  -H 'authorization: Basic Zm9zc3k6Zm9zc3k=' \
  -H 'Content-Type: application/json' \
  -d '{
  "marydone": false,
  "rf_FSFfree": null,
  "rf_Fedora": null,
  "rf_GPLv2compatible": null,
  "rf_GPLv3compatible": null,
  "rf_OSIapproved": null,
  "rf_active": true,
  "rf_add_date": "2023-12-01T18:10:25.00+05:30",
  "rf_copyleft": null,
  "rf_detector_type": 1,
  "rf_flag": 1,
  "rf_fullname": "GNU General Public License v2.0 w\/Autoconf exception",
  "rf_notes": "GNU General Public License v2.0 w\/Autoconf exception",
  "rf_risk": null,
  "rf_shortname": "GPL-2.0-with-autoconf-exception",
  "rf_source": null,
  "rf_spdx_id": "MIT",
  "rf_text": "insert GPL v2 license text here\n\nAutoconf Exception\n\nAs a special exception, the Free Software Foundation gives unlimited permission to copy, distribute and modify the configure scripts that are the output of Autoconf. You need not follow the terms of the GNU General Public License when using or distributing such scripts, even though portions of the text of Autoconf appear in them. The GNU General Public License (GPL) does govern all other use of the material that constitutes the Autoconf program.\n\nCertain portions of the Autoconf source text are designed to be copied (in certain cases, depending on the input) into the output of Autoconf. We call these the \"data\" portions. The rest of the Autoconf source text consists of comments plus executable code that decides which of the data portions to output in any given case. We call these comments and executable code the \"non-data\" portions. Autoconf never copies any of the non-data portions into its output.\n\nThis special exception to the GPL applies to versions of Autoconf released by the Free Software Foundation. When you make and distribute a modified version of Autoconf, you may extend this special exception to the GPL to apply to your modified version as well, *unless* your modified version has the potential to copy into its output some of the text that was the non-data portion of the version that you started with. (In other words, unless your change moves or copies text from the non-data portions to the data portions.) If your modification has such potential, you must delete any notice of this special exception to the GPL from your modified version.\n\n",
  "rf_text_updatable": false,
  "rf_url": "http:\/\/ac-archive.sourceforge.net\/doc\/copyright.html"
}'

Tell me if this suffices.

![Screenshot from 2024-01-04 12-43-17](https://github.com/fossology/LicenseDb/assets/25108210/cd681a71-81b4-4ab9-bb7e-ee704b42b9ee)

**Comment by dvjsharma** [comment]
Hello @GMishx,

I noticed a potential issue in the authentication middleware, the `err` variable is used inconsistently. Please refer to the snippet below- 
https://github.com/fossology/LicenseDb/blob/aa42310676d7cf70a3319d11624bc74dc29372b8/pkg/auth/auth.go#L194-L207
Here the `err` variable err is appropriately used to capture potential errors during the base64 decoding process, but it is incorrectly used further in the code. 
https://github.com/fossology/LicenseDb/blob/aa42310676d7cf70a3319d11624bc74dc29372b8/pkg/auth/auth.go#L219-L247
At line 224, `err.Error()` references to decoding errors but it should be referencing to the errors occurring during GORM db querying process occurring at line 219, Hence it should be replaced by `result.Error.Error()` to deliever GORM specific errors. This might solve the nil pointer dereference issue.

Furthermore, line 239 should also be modified to give 'password mismatch/incorrect' error rather than `err.Error()`.

If you are good with the solution i'll open up a pull request. Please take a look.
Thanks!

**Comment by GMishx** [comment]
Oh, it looks correct @dvjsharma . Please go ahead with the PR.
